import guidesData from "@/data/teacher_guides.json";

/**
 * Teacher's-guide lookup, keyed by lowercased SKU.
 *
 * Source of truth is `src/data/teacher_guides.json`, generated by
 * `scripts/build-teacher-guides.ts` from NetSuite. That script keeps ONLY URLs
 * that actually return a PDF (public File Cabinet docs), so anything here is safe
 * to link — login-gated / dead / mis-keyed URLs are excluded upstream. Regenerate
 * after fixing "Available Without Login" on a File Cabinet doc to light it up.
 *
 * The URLs are server-side only (used by /api/teacher-guide to proxy the PDF);
 * the storefront just needs the booleans, so this map is never shipped to the
 * client.
 */
type Doc = "guide" | "handout";
interface Entry {
	guide?: string;
	handout?: string;
}

const MAP = guidesData as Record<string, Entry>;

/** The validated PDF URL for a SKU's guide/handout, or null if none works. */
export function teacherGuideUrl(sku: string, doc: Doc = "guide"): string | null {
	return MAP[sku.trim().toLowerCase()]?.[doc] ?? null;
}

/** Whether a SKU has a working teacher's guide (for gating the UI buttons). */
export function hasTeacherGuide(sku: string): boolean {
	return Boolean(MAP[sku.trim().toLowerCase()]?.guide);
}
